name: Build Android App Bundle

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Keystore file
        run: |
          printf "%s" "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d -i > android.keystore

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Debug - List Files
        run: ls -R

      - name: Build PAGO Version
        run: |
          bubblewrap doctor --jdkPath "$JAVA_HOME" --androidSdkPath "$ANDROID_HOME"
          yes "" | bubblewrap build --signingKeyPath android.keystore --signingKeyAlias "android" --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" --keyStorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --skip-directory-check
          for f in *.apk; do mv "$f" "Pastores-PAGO.apk"; break; done
          for f in *.aab; do mv "$f" "Pastores-PAGO.aab"; break; done

      - name: Switch to CORTESIA Mode
        run: |
          sed -i 's/const IS_FREE_VERSION = false/const IS_FREE_VERSION = true/g' app.js

      - name: Build CORTESIA Version
        run: |
          yes "" | bubblewrap build --signingKeyPath android.keystore --signingKeyAlias "android" --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" --keyStorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --skip-directory-check
          for f in *.apk; do mv "$f" "Pastores-CORTESIA.apk"; break; done
          for f in *.aab; do mv "$f" "Pastores-CORTESIA.aab"; break; done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Versoes-Android-Pastores
          path: |
            Pastores-PAGO.apk
            Pastores-PAGO.aab
            Pastores-CORTESIA.apk
            Pastores-CORTESIA.aab
