name: Build Android App Bundle

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Keystore file
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Build AAB using Bubblewrap
        run: |
          npm install -g @bubblewrap/cli
          bubblewrap doctor --jdkPath "$JAVA_HOME" --androidSdkPath "$ANDROID_HOME"
          printf "n\nn\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | bubblewrap init --manifest https://app-igreja-red.vercel.app/manifest.json
          bubblewrap build --signingKeyPath my-release-key.keystore --signingKeyAlias "${{ secrets.ANDROID_KEY_ALIAS }}" --signingKeyPassword "${{ secrets.ANDROID_KEY_PASSWORD }}" --keyStorePassword "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --skip-directory-check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-package
          path: |
            *.aab
            *.apk
